#!/bin/bash
# Lockdown initialization function
lockdown_init () {
  if [ ! -d /usr/sbin ]
  then
    mkdir -p /usr/sbin
  fi
  if [ -d /usr/sbin ]
  then
    chmod u+x bin/*
    cp bin/* /usr/sbin
  else
    echo "Could not create or access /usr/sbin, installation cannot continue"
    exit 1
  fi
  if [ ! -d /etc/lockdown ]
  then
    mkdir -p /etc/lockdown
  fi
  if [ ! -d /etc/lockdown/archives ]
  then
    mkdir -p /etc/lockdown/archives
  fi
  if [ ! -d /etc/lockdown/blacklist-ips ]
  then
    mkdir -p /etc/lockdown/blacklist-ips
    touch /etc/lockdown/blacklist-ips/entries.txt
  fi
  if [ ! -d /etc/lockdown/blacklist-net ]
  then
    mkdir -p /etc/lockdown/blacklist-net
    touch /etc/lockdown/blacklist-net/entries.txt
  fi
  if [ ! -d /etc/lockdown/whitelist-ips ]
  then
    mkdir -p /etc/lockdown/whitelist-ips
    touch /etc/lockdown/whitelist-ips/entries.txt
  fi
  if [ ! -d /etc/lockdown/whitelist-net ]
  then
    mkdir -p /etc/lockdown/whitelist-net
    touch /etc/lockdown/whitelist-net/entries.txt
  fi
  if [ -d /etc/lockdown ]
  then
    /bin/cp -r $SRCDIR/conf /etc/lockdown
    /bin/cp -r $SRCDIR/lists /etc/lockdown
    /bin/cp -r $SRCDIR/post-process /etc/lockdown
    /bin/cp -r $SRCDIR/pre-process /etc/lockdown
    /bin/cp -r $SRCDIR/etc/ipset.conf /etc/
    chown root:root /etc/ipset.conf
  else
    echo "Could not create or access /etc/lockdown, installation cannot continue"
    exit 1
  fi
  if [ -d /etc/sysconfig ]
  then
      /bin/cp -r $SRCDIR/etc/sysconfig/* /etc/sysconfig/
      chown root:root /etc/sysconfig/iptable*
  else
      echo "Could not install iptables configuration files, cannot continue"
      exit 1
  fi
  if [ -d /etc/systemd ]
  then
    echo "Upstart discovered, installing service units"
    /bin/cp -r $SRCDIR/usr/* /usr/
    chown -R root:root /usr/libexec/ip* /usr/lib/systemd/system/ip*
    chmod u+x /usr/libexec/iptables/* /usr/libexec/ipset/ipset.start-stop /usr/lib/systemd/system/ip*
  elif [ -d /etc/init.d ]
  then
    echo "SysV init discovered, installing init files"
    /bin/cp $SRCDIR/etc/init.d/ipset /etc/init.d/
    chown -R root:root /etc/lockdown /etc/init.d/ipset
    chmod u+x /etc/init.d/ipset
  else
    echo "Could not determine system initialization method, cannot continue"
    exit 1
  fi
  if [ ! -d /usr/local/share/lockdown ]
  then
    mkdir -p /usr/local/share/lockdown
  fi
  if [ -d /usr/local/share/lockdown ]
  then
    /bin/cp -r $SRCDIR/* /usr/local/share/lockdown/
    chmod u+x /usr/local/share/lockdown/bin/*
    chmod u+x /usr/local/share/lockdown/lib/*
  else
    echo "Could not create or access /usr/local/share/lockdown, installation cannot continue"
    exit 1
  fi
}
