#!/bin/bash
#   Amazon Linux, CentOS
#     service x start|stop|etc
#     chkconfig x on|off
# Begin starting services
if (( ! SILENT )) ; then echo "Starting services for $DISTRO"; fi
$1 service fail2ban start
if [ 0 -ne $? ] && [ -z $1 ]
then
    echo "Failed to start fail2ban, exiting."
    exit 1
fi
$1 service ipset start
if [ 0 -ne $? ] && [ -z $1 ]
then
    echo "Failed to start ipset, exiting."
    exit 1
fi
$1 service iptables start
if [ 0 -ne $? ] && [ -z $1 ]
then
    echo "Failed to start iptables, exiting."
    exit 1
fi
# Begin stopping & disabling conflicting services
if [ `pidof nftables` ]
then
  if (( ! SILENT )) ; then echo "Stopping & disabling nftables"; fi
  $1 service nftables stop
  $1 chkconfig nftables off
fi
if [ `pidof firewalld` ]
then
  if (( ! SILENT )) ; then echo "Stopping & disabling firewalld"; fi
  $1 service firewalld stop
  $1 chkconfig firewalld off
fi
# Begin enabling services
if (( ! SILENT )) ; then echo "Enabling services for $DISTRO"; fi
$1 chkconfig fail2ban on
if [ 0 -ne $? ] && [ -z $1 ]
then
    echo "Failed to enable fail2ban, exiting."
fi
$1 chkconfig ipset on
if [ 0 -ne $? ] && [ -z $1 ]
then
    echo "Failed to enable ipset, exiting."
fi
$1 chkconfig iptables on
if [ 0 -ne $? ] && [ -z $1 ]
then
    echo "Failed to enable iptables, exiting."
fi
if (( ! SILENT )) ; then echo "Service configuration completed successfully!"; fi

