#!/bin/bash
# Amazon Linux 2, Fedora, RHEL, Ubuntu
#   systemctl start|stop|etc x
#   systemctl enable|disable x
# Begin starting services
if (( ! SILENT )) ; then echo "Starting systemctl"; fi
systemctl start fail2ban
if [ 0 -ne $? ] && [ -z ]
then
    echo "Failed to start fail2ban, exiting."
    exit 1
fi
systemctl start ipset
if [ 0 -ne $? ] && [ -z ]
then
    echo "Failed to start ipset, exiting."
    exit 1
fi
systemctl start iptables
if [ 0 -ne $? ] && [ -z ]
then
    echo "Failed to start iptables, exiting."
    exit 1
fi
# Begin stopping & disabling conflicting services
if [ `pidof nftables` ]
then
  if (( ! SILENT )) ; then echo "Stopping & disabling nftables"; fi
  systemctl stop nftables
  systemctl disable nftables
fi
if [ `pidof firewalld` ]
then
  if (( ! SILENT )) ; then echo "Stopping & disabling firewalld"; fi
  systemctl stop nftables
  systemctl disable nftables
fi
# Begin enabling services
if (( ! SILENT )) ; then echo "Enabling services"; fi
systemctl enable fail2ban
if (( `systemctl is-enabled fail2ban` )) && [ -z ]
then
    echo "Failed to enable fail2ban, exiting."
fi
systemctl enable ipset
if (( `systemctl is-enabled ipset` )) && [ -z ]
then
    echo "Failed to enable fail2ban, exiting."
fi
systemctl enable iptables
if (( `systemctl is-enabled iptables` )) && [ -z ]
then
    echo "Failed to enable fail2ban, exiting."
fi
if (( ! SILENT )) ; then echo "Service configuration completed successfully!"; fi
