#!/bin/bash
# Report installation status
installation_report () {
  # Check for executables & required directories
  if [ ! -z `whereis iptables | cut -d: -f2` ]
  then
    echo "iptables found"
  else
    "Could not find iptables, please report on Github issues"
    exit 1
  fi
  if [ ! -z `whereis ipset | cut -d: -f2` ]
  then
    echo "ipset found"
  else
    "Could not find ipset, please report on Github issues"
    exit 1
  fi
  if [ ! -z `whereis fail2ban-server | cut -d: -f2` ]
  then
    echo "fail2ban-server found"
  else
    echo "Could not find fail2ban, please report on Github issues"
    exit 1
  fi
  if [ -d /etc/fail2ban ]
  then
    echo "/etc/fail2ban found"
  else
    "Could not find fail2ban configuration files, please report on Github issues"
    exit 1
  fi
  if [ -d /etc/lockdown ]
  then
    echo "/etc/lockdown found"
  else
    "Could not find Lockdown configuration files, please report on Github issues"
    exit 1
  fi
  if [ -d /usr/local/share/lockdown ]
  then
    echo "/usr/local/share/lockdown found"
  else
    "Could not find Lockdown shared files, please report on Github issues"
    exit 1
  fi
  if [ -f /usr/sbin/ld-allow ]
  then
    echo "/etc/lockdown found"
  else
    "Could not find Lockdown configuration files, please report on Github issues"
    exit 1
  fi

  # Make sure everything is A-OK (ld-test should exit 0 status w/no output)
  if (( `/usr/sbin/ld-test` ))
  then
    "Lockdown test failed, please report on Github issues"
    exit 1
  else
    echo "Lockdown test passed."
  fi

  # Display success message and show user relevant files
  echo
  echo
  echo "Lockdown executables are in /usr/sbin and start with ld-"
  echo ">> ls /usr/sbin/ld-*:"
  ls /usr/sbin/ld-*
  echo
  echo "Lockdown configuration files are in /etc/lockdown"
  echo ">> ls /etc/lockdown:"
  ls /etc/lockdown
  echo
  echo "Lockdown blacklist & country files are in /usr/share/lockdown"
  echo ">> ls /usr/share/lockdown:"
  ls /usr/local/share/lockdown
  echo
  echo "Success!"
  echo "May the force of my ban hammer be with you! - @iDoMeteor"
  echo
}
